implemented
japan-expert-force/data-structure pull request #3
Opened 2021-05-31 11:06 UTC by Realitive-jef

以下のファイルをタスク内容どおりに実装した
Queue.js
Array.js
結局一人だとよく分からなかったのでProgate課金して配列とオブジェクトの部分を学習して書いた。
一応`npx mocha test/Array`と`npx mocha test/Queue`を実行して全てパスできてる。

2021-05-31 11:08 UTC, Realitive-jef commented
なんかよくわからないファイルが3,600個ぐらい消えようとしてる...

2021-06-01 12:01 UTC, sharo-jef requested changes

2021-06-01 12:01 UTC, sharo-jef commented on Queue/Queue.js
> +        for (let i < this.queueArray.length; i++) {
Syntax Error

2021-06-02 02:25 UTC, sharo-jef requested changes

2021-06-02 02:25 UTC, sharo-jef commented on Queue/Queue.js
> +        for (let i =0 ; i < this.queueArray.length; i++) {
Invalid style
```javascript
i = 0
```

2021-06-02 11:42 UTC, Realitive-jef commented on Queue/Queue.js
> +        for (let i =0 ; i < this.queueArray.length; i++) {
あっ直したのにプッシュしてなかった

2021-06-02 15:23 UTC, sharo-jef requested changes
zako がよ

2021-06-02 15:23 UTC, sharo-jef commented on Queue/Queue.js
> +        for (let i =0; i < this.queueArray.length; i++) {
```javascript
i = 0;
```

2021-06-02 18:28 UTC, Realitive-jef commented
; ;

2021-06-04 19:38 UTC, sharo-jef approved these changes

2021-06-04 19:38 UTC, closed without merging